# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1233, 805)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 80, 1011, 621))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButtonGPIO_02 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_02.setGeometry(QtCore.QRect(10, 170, 81, 21))
        self.pushButtonGPIO_02.setStyleSheet("")
        self.pushButtonGPIO_02.setObjectName("pushButtonGPIO_02")
        self.pushButtonGPIO_03 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_03.setGeometry(QtCore.QRect(10, 200, 81, 21))
        self.pushButtonGPIO_03.setObjectName("pushButtonGPIO_03")
        self.pushButtonGPIO_04 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_04.setGeometry(QtCore.QRect(10, 230, 81, 21))
        self.pushButtonGPIO_04.setObjectName("pushButtonGPIO_04")
        self.pushButtonGPIO_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_27.setGeometry(QtCore.QRect(10, 300, 81, 21))
        self.pushButtonGPIO_27.setObjectName("pushButtonGPIO_27")
        self.pushButtonGPIO_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_17.setGeometry(QtCore.QRect(10, 270, 81, 21))
        self.pushButtonGPIO_17.setObjectName("pushButtonGPIO_17")
        self.pushButtonGPIO_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_22.setGeometry(QtCore.QRect(10, 330, 81, 21))
        self.pushButtonGPIO_22.setObjectName("pushButtonGPIO_22")
        self.pushButtonGPIO_09 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_09.setGeometry(QtCore.QRect(10, 410, 81, 21))
        self.pushButtonGPIO_09.setObjectName("pushButtonGPIO_09")
        self.pushButtonGPIO_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_10.setGeometry(QtCore.QRect(10, 380, 81, 21))
        self.pushButtonGPIO_10.setObjectName("pushButtonGPIO_10")
        self.pushButtonGPIO_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_11.setGeometry(QtCore.QRect(10, 440, 81, 21))
        self.pushButtonGPIO_11.setObjectName("pushButtonGPIO_11")
        self.pushButtonGPIO_06 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_06.setGeometry(QtCore.QRect(10, 540, 81, 21))
        self.pushButtonGPIO_06.setObjectName("pushButtonGPIO_06")
        self.pushButtonGPIO_05 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_05.setGeometry(QtCore.QRect(10, 510, 81, 21))
        self.pushButtonGPIO_05.setObjectName("pushButtonGPIO_05")
        self.pushButtonGPIO_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_13.setGeometry(QtCore.QRect(10, 570, 81, 21))
        self.pushButtonGPIO_13.setObjectName("pushButtonGPIO_13")
        self.pushButtonGPIO_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_15.setGeometry(QtCore.QRect(1140, 250, 81, 21))
        self.pushButtonGPIO_15.setObjectName("pushButtonGPIO_15")
        self.pushButtonGPIO_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_14.setGeometry(QtCore.QRect(1140, 220, 81, 21))
        self.pushButtonGPIO_14.setObjectName("pushButtonGPIO_14")
        self.pushButtonGPIO_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_18.setGeometry(QtCore.QRect(1140, 280, 81, 21))
        self.pushButtonGPIO_18.setObjectName("pushButtonGPIO_18")
        self.pushButtonGPIO_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_26.setGeometry(QtCore.QRect(10, 630, 81, 21))
        self.pushButtonGPIO_26.setObjectName("pushButtonGPIO_26")
        self.pushButtonGPIO_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_19.setGeometry(QtCore.QRect(10, 600, 81, 21))
        self.pushButtonGPIO_19.setObjectName("pushButtonGPIO_19")
        self.pushButtonGPIO_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_20.setGeometry(QtCore.QRect(1140, 630, 81, 21))
        self.pushButtonGPIO_20.setObjectName("pushButtonGPIO_20")
        self.pushButtonGPIO_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_16.setGeometry(QtCore.QRect(1140, 600, 81, 21))
        self.pushButtonGPIO_16.setObjectName("pushButtonGPIO_16")
        self.pushButtonGPIO_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_21.setGeometry(QtCore.QRect(1140, 660, 81, 21))
        self.pushButtonGPIO_21.setObjectName("pushButtonGPIO_21")
        self.pushButtonGPIO_08 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_08.setGeometry(QtCore.QRect(1140, 440, 81, 21))
        self.pushButtonGPIO_08.setObjectName("pushButtonGPIO_08")
        self.pushButtonGPIO_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_25.setGeometry(QtCore.QRect(1140, 410, 81, 21))
        self.pushButtonGPIO_25.setObjectName("pushButtonGPIO_25")
        self.pushButtonGPIO_07 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_07.setGeometry(QtCore.QRect(1140, 470, 81, 21))
        self.pushButtonGPIO_07.setObjectName("pushButtonGPIO_07")
        self.pushButtonGPIO_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_24.setGeometry(QtCore.QRect(1140, 360, 81, 21))
        self.pushButtonGPIO_24.setStyleSheet("")
        self.pushButtonGPIO_24.setObjectName("pushButtonGPIO_24")
        self.pushButtonGPIO_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_23.setGeometry(QtCore.QRect(1140, 330, 81, 21))
        self.pushButtonGPIO_23.setObjectName("pushButtonGPIO_23")
        self.pushButtonGPIO_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGPIO_12.setGeometry(QtCore.QRect(1140, 540, 81, 21))
        self.pushButtonGPIO_12.setObjectName("pushButtonGPIO_12")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 30, 371, 21))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Raspberry Pi 2 Model B Pin Selector"))
        self.pushButtonGPIO_02.setText(_translate("MainWindow", "GPIO02"))
        self.pushButtonGPIO_03.setText(_translate("MainWindow", "GPIO03"))
        self.pushButtonGPIO_04.setText(_translate("MainWindow", "GPIO04"))
        self.pushButtonGPIO_27.setText(_translate("MainWindow", "GPIO27"))
        self.pushButtonGPIO_17.setText(_translate("MainWindow", "GPIO17"))
        self.pushButtonGPIO_22.setText(_translate("MainWindow", "GPIO22"))
        self.pushButtonGPIO_09.setText(_translate("MainWindow", "GPIO09"))
        self.pushButtonGPIO_10.setText(_translate("MainWindow", "GPIO10"))
        self.pushButtonGPIO_11.setText(_translate("MainWindow", "GPIO11"))
        self.pushButtonGPIO_06.setText(_translate("MainWindow", "GPIO06"))
        self.pushButtonGPIO_05.setText(_translate("MainWindow", "GPIO05"))
        self.pushButtonGPIO_13.setText(_translate("MainWindow", "GPIO13"))
        self.pushButtonGPIO_15.setText(_translate("MainWindow", "GPIO15"))
        self.pushButtonGPIO_14.setText(_translate("MainWindow", "GPIO14"))
        self.pushButtonGPIO_18.setText(_translate("MainWindow", "GPIO18"))
        self.pushButtonGPIO_26.setText(_translate("MainWindow", "GPIO26"))
        self.pushButtonGPIO_19.setText(_translate("MainWindow", "GPIO19"))
        self.pushButtonGPIO_20.setText(_translate("MainWindow", "GPIO20"))
        self.pushButtonGPIO_16.setText(_translate("MainWindow", "GPIO16"))
        self.pushButtonGPIO_21.setText(_translate("MainWindow", "GPIO21"))
        self.pushButtonGPIO_08.setText(_translate("MainWindow", "GPIO08"))
        self.pushButtonGPIO_25.setText(_translate("MainWindow", "GPIO25"))
        self.pushButtonGPIO_07.setText(_translate("MainWindow", "GPIO07"))
        self.pushButtonGPIO_24.setText(_translate("MainWindow", "GPIO24"))
        self.pushButtonGPIO_23.setText(_translate("MainWindow", "GPIO23"))
        self.pushButtonGPIO_12.setText(_translate("MainWindow", "GPIO12"))
        self.label_2.setText(_translate("MainWindow", "Toggle the desired pins on and off using the buttons"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

