import sys
import os

class ProjectDirectory:
    def __init__(self):
        self.PROJECT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
        sys.path.append(self.PROJECT_DIRECTORY)
        sys.path.append(os.path.join(self.PROJECT_DIRECTORY, 'AutoGeneratedCode'))
        sys.path.append(os.path.join(self.PROJECT_DIRECTORY, 'Images'))
        sys.path.append(os.path.join(self.PROJECT_DIRECTORY, 'ImplementedCode'))
        sys.path.append(os.path.join(self.PROJECT_DIRECTORY, 'UiFiles'))
        
    def setUpPaths(self, path):
        self.PROJECT_DIRECTORY = path
        sys.path.append(self.PROJECT_DIRECTORY)
        sys.path.append(os.path.join(self.PROJECT_DIRECTORY, 'AutoGeneratedCode'))
        sys.path.append(os.path.join(self.PROJECT_DIRECTORY, 'Images'))
        sys.path.append(os.path.join(self.PROJECT_DIRECTORY, 'ImplementedCode'))
        sys.path.append(os.path.join(self.PROJECT_DIRECTORY, 'UiFiles'))
