#!/usr/bin/env python3
import sys
import os
from PathManager import ProjectDirectory

PROJECT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
sys.path.append(PROJECT_DIRECTORY)
sys.path.append(os.path.join(PROJECT_DIRECTORY, 'AutoGeneratedCode'))
sys.path.append(os.path.join(PROJECT_DIRECTORY, 'Images'))
sys.path.append(os.path.join(PROJECT_DIRECTORY, 'ImplementedCode'))
sys.path.append(os.path.join(PROJECT_DIRECTORY, 'UiFiles'))

from PyQt5                      import QtWidgets
from PyQt5.QtWidgets            import QMainWindow, QApplication

from AutoGeneratedMainWindow 	import Ui_MainWindow
from MainWindow                 import MainWindow



if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)

    projectDirectory = ProjectDirectory()
    mainWindow = MainWindow(projectDirectory)

    sys.exit(app.exec_())
